In [1]:
import pyspark

In [2]:
import pandas as pd

In [9]:
pd.read_csv("mtcars.csv")

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [10]:
# importing spark sesssion 
from pyspark.sql import SparkSession

In [11]:
#creating Variable
spark = SparkSession.builder.appName('Practice').getOrCreate()

In [12]:
spark

In [16]:
# read dataset with pyspark
df_pyspark=spark.read.csv("mtcars.csv")

In [17]:
df_pyspark

DataFrame[_c0: string, _c1: string, _c2: string, _c3: string, _c4: string, _c5: string, _c6: string, _c7: string, _c8: string, _c9: string, _c10: string]

In [19]:
df_pyspark.show(10)

+----+---+-----+---+----+-----+-----+---+---+----+----+
| _c0|_c1|  _c2|_c3| _c4|  _c5|  _c6|_c7|_c8| _c9|_c10|
+----+---+-----+---+----+-----+-----+---+---+----+----+
| mpg|cyl| disp| hp|drat|   wt| qsec| vs| am|gear|carb|
|  21|  6|  160|110| 3.9| 2.62|16.46|  0|  1|   4|   4|
|  21|  6|  160|110| 3.9|2.875|17.02|  0|  1|   4|   4|
|22.8|  4|  108| 93|3.85| 2.32|18.61|  1|  1|   4|   1|
|21.4|  6|  258|110|3.08|3.215|19.44|  1|  0|   3|   1|
|18.7|  8|  360|175|3.15| 3.44|17.02|  0|  0|   3|   2|
|18.1|  6|  225|105|2.76| 3.46|20.22|  1|  0|   3|   1|
|14.3|  8|  360|245|3.21| 3.57|15.84|  0|  0|   3|   4|
|24.4|  4|146.7| 62|3.69| 3.19|   20|  1|  0|   4|   2|
|22.8|  4|140.8| 95|3.92| 3.15| 22.9|  1|  0|   4|   2|
+----+---+-----+---+----+-----+-----+---+---+----+----+
only showing top 10 rows

In [29]:
df_pyspark=spark.read.option('header','true').csv('mtcars.csv')   # want first row as a header then ....

In [30]:
spark.read.option('header','true').csv('mtcars.csv').show(10)   # store in de_pyspark

+----+---+-----+---+----+-----+-----+---+---+----+----+
| mpg|cyl| disp| hp|drat|   wt| qsec| vs| am|gear|carb|
+----+---+-----+---+----+-----+-----+---+---+----+----+
|  21|  6|  160|110| 3.9| 2.62|16.46|  0|  1|   4|   4|
|  21|  6|  160|110| 3.9|2.875|17.02|  0|  1|   4|   4|
|22.8|  4|  108| 93|3.85| 2.32|18.61|  1|  1|   4|   1|
|21.4|  6|  258|110|3.08|3.215|19.44|  1|  0|   3|   1|
|18.7|  8|  360|175|3.15| 3.44|17.02|  0|  0|   3|   2|
|18.1|  6|  225|105|2.76| 3.46|20.22|  1|  0|   3|   1|
|14.3|  8|  360|245|3.21| 3.57|15.84|  0|  0|   3|   4|
|24.4|  4|146.7| 62|3.69| 3.19|   20|  1|  0|   4|   2|
|22.8|  4|140.8| 95|3.92| 3.15| 22.9|  1|  0|   4|   2|
|19.2|  6|167.6|123|3.92| 3.44| 18.3|  1|  0|   4|   4|
+----+---+-----+---+----+-----+-----+---+---+----+----+
only showing top 10 rows

In [31]:
type(df_pyspark)

pyspark.sql.dataframe.DataFrame

In [34]:
df_pyspark.head()

Row(mpg='21', cyl='6', disp='160', hp='110', drat='3.9', wt='2.62', qsec='16.46', vs='0', am='1', gear='4', carb='4')

In [35]:
df_pyspark.head(4)

[Row(mpg='21', cyl='6', disp='160', hp='110', drat='3.9', wt='2.62', qsec='16.46', vs='0', am='1', gear='4', carb='4'),
 Row(mpg='21', cyl='6', disp='160', hp='110', drat='3.9', wt='2.875', qsec='17.02', vs='0', am='1', gear='4', carb='4'),
 Row(mpg='22.8', cyl='4', disp='108', hp='93', drat='3.85', wt='2.32', qsec='18.61', vs='1', am='1', gear='4', carb='1'),
 Row(mpg='21.4', cyl='6', disp='258', hp='110', drat='3.08', wt='3.215', qsec='19.44', vs='1', am='0', gear='3', carb='1')]

In [36]:
df_pyspark.printSchema   # just like a df.info